version: '3.5'

services: 
  pizzaria-db:
    container_name: pizzaria-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD-pizzaria123}
      - POSTGRES_DB=pizzaria
    healthcheck:
      test: 'pg_isready -U postgres'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - default
    restart: unless-stopped
networks:
  default:
    driver: bridge